name: pianote
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  getwidget: ^4.0.0
  open_file: ^3.3.2
  path_provider: ^2.1.2
  path_provider_platform_interface: ^2.1.2
  pdfrx: ^1.0.51
  scroll_snap_list: ^0.9.1
  unicons: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  flutter_screenutil: any
  flutter_sizer: any

flutter:
  uses-material-design: true

  assets:
    - assets/